### ISSUE TITLE
roslaunch loop_fusion posegraph 

### ISSUE THREAD

**Issue by uts-hb** [rpng/ov_secondary#4]
Hi, I am just trying to run it with the V1_01_easy.bag file. 
But had an issue with launching the loop_fusion pose graph showing [POSEGRAPH]: waiting for camera info topic... .

**Comment by uts-hb** [comment]
Solved by changing topics in posegraph.launch.
 From 

        <remap from="/vins_estimator/extrinsic"        to="/ov_msckf/keyframe_extrinsic"/>
        <remap from="/vins_estimator/keyframe_point"   to="/ov_msckf/keyframe_feats"/>
        <remap from="/vins_estimator/keyframe_pose"    to="/ov_msckf/keyframe_pose"/>
        <remap from="/vins_estimator/intrinsics"       to="/ov_msckf/keyframe_intrinsics"/>

To

        <remap from="/vins_estimator/extrinsic"        to="/ov_msckf/loop_extrinsic"/>
        <remap from="/vins_estimator/keyframe_point"   to="/ov_msckf/loop_feats"/>
        <remap from="/vins_estimator/keyframe_pose"    to="/ov_msckf/loop_pose"/>
        <remap from="/vins_estimator/intrinsics"       to="/ov_msckf/loop_intrinsics"/>

**Comment by goldbattle** [comment]
I should fix the launch file, will re-open so I remember to do this.
Thanks!

**Comment by HuZexild** [comment]
> 

I am facing this problem too, however, I tried the method you provided that change "keyframe" into "loop", it still shows waiting for camera info topic...

**Comment by shervinkoushan** [comment]
> > 
> 
> I am facing this problem too, however, I tried the method you provided that change "keyframe" into "loop", it still shows waiting for camera info topic...

Same issue here with the latest master of OpenVINS. @goldbattle do you know how to solve this problem?

By the way, `pgeneva_ros_eth.launch` does not currently exist in the `ov_msckf` package.

**Edit**
Seems to work after all by running  `ov_msckf subscribe.launch` with the above fix. However, it takes around 10 seconds before the pose graph receives the camera info message.
